### ISSUE TITLE
PM Review #1: Design Documents/Wiki

### ISSUE THREAD

**Issue by andrewlangston** [gameguy37/goDutch#1]
Hi Jon,

Great job with your design documents. Some preliminary comments on what you've been assigned thus far (MVP list, schema, sample state):

**MVP LIST**
- [x] I suspect that bills may take more than a single day to implement. Let's adjust this timeline so that both bills and transaction histories are allotted two days each. Note that this timeline can be adjusted as your work proceeds - it is, more than anything else, a pacing guide.

**SCHEMA**
- [x] Let's add notes about model associations here. Which foreign keys reference which tables in your database? (For example, in your `friendships` table, both `user_id` and `friend_id` reference the `users` table.)
- [x] On your `bills` table, is the `settled` column strictly necessary? It seems we can tell a bill is settled when its `balance` is zero.
- [x] Similarly, on your `payments` table, do we need a `paid` column? I am inclined to air on the side of recording a `payment` only when it is, in fact, paid. Let me know what your thoughts are here.

**SAMPLE STATE**
- [x] One note on formatting: our JavaScript object keys should be `camelCased`, not `snake_cased` or a `combinationOf_theTwo`.
- [x] `users` should each have a `friendIds` array to reference other users with which they have a `friendship`.
- [x] Pursuant to the above, we shouldn't need the `friendships` slice of state at all. Information about how users are connected can be held entirely in the `users` slice of state.
- [x] Regarding your notes in the `bills` slice of state, I think you are correct to consider more semantic terminology for those who create bills and those who pay them. Perhaps `billerId` and `billeeIds` would suffice - I leave the decision up to you.
- [x] `bills` should also hold reference to associated `payments` via an array of IDs.

Please don't hesitate to reach out here (or via Slack) with questions.

**Comment by gameguy37** [comment]
I really appreciate these comments, they've helped me hone in on some of the more complicated aspects of how this all is going to work on the backend.

I left the one box unchecked since I can't wrap my head around how it can be avoided. I create a bill for $300 because I went to dinner with 2 friends, Tom and Sally. Right away, the bill ($300) is split into 3 parts, 1 for each participant (whether they are the biller or the billee). 

Because the bill knows I'm the biller and I'm not going to pay myself, payments are only created for participants who are not the biller. So in this case, Tom and Sally both are associated with payments to this bill for $100 each, which is money that I need to know I am owed as the biller. The "balance" on the bill is now $200, which is the sum of all outstanding payments (ones with "paid" flags set to false). I think it's required that the paid boolean flag exists so that the bill can track how much money is still owed to me for as long as I remain unpaid by these 2 (delinquent) billees.

However, I'd be very happy to talk about how to accomplish this without holding reference to whether payments are ever followed-through on.

**Comment by andrewlangston** [comment]
Hi Jon - thanks for the quick turnaround. Let's meet to discuss bills & payments come Monday, as I think there are several valid approaches that we can talk through before settling on a way forward.

In the meantime, some additional comments on your route design documents:

**BACKEND ROUTES**
- [ ] Recall that `GET /api/users` would be the route for a controller `#index` action, which should return a collection of many users. Is this what you intended?
- [ ] You shouldn't need a `GET /api/friendships` route, as you needn't hold friendships in frontend state.
- [ ] Will you ever need to fetch a single payment via `GET /api/payments/:id`? My guess is no. It would probably make more sense for `GET /api/payments` to serve up information about payments related to a particular bill (which may coincidentally involve a single payment).
- [ ] Will you need an API endpoint through which to edit comments?

**FRONTEND ROUTES**
- [ ] Splitwise uses a drodown for logging in - not an entirely new frontend route. You can remove `/login`.
